### ISSUE TITLE
User can register new systems with Agave through IDS

### ISSUE THREAD

**Issue by ramonawalls** [andrewmagill/Identifier-Services-Portal#14]
This does not have to be for any location, just for systems that can be registered with Agave.

**Comment by ramonawalls** [comment]
@mesteva - tell me if you agree.

I don't think they need to be able to do the Agave registration through the portal. I think it is enough to be able to register a system with Agave using the CLI or CURL, and then they should be able to register a file that is on that system through the portal.

**Comment by mesteva** [comment]
I do!

Sent from my iPhone

On Jul 5, 2016, at 5:05 PM, Ramona Walls <notifications@github.com<mailto:notifications@github.com>> wrote:

@mestevahttps://github.com/mesteva - tell me if you agree.

I don't think they need to be able to do the Agave registration through the portal. I think it is enough to be able to register a system with Agave using the CLI or CURL, and then they should be able to register a file that is on that system through the portal.

##

**Comment by ramonawalls** [comment]
Great! Then as soon as the documentation is ready, we can close this issue.

**Comment by ramonawalls** [comment]
Documentation is here: https://github.com/identifier-services/Identifier-Services-Portal/wiki/Registering-a-Storage-System-in-Agave
