### ISSUE TITLE
Define Agave app to download sequencing data from NCBI 

### ISSUE THREAD

**Issue by ramonawalls** [andrewmagill/Identifier-Services-Portal#16]
See documentation for ASCP (Asperca Connect) at:

http://www.ncbi.nlm.nih.gov/books/NBK242625/
http://download.asperasoft.com/download/docs/ascp/3.5.2/html/index.html

Should first confirm that ascp is the best way to go.

**Comment by ramonawalls** [comment]
Be able to get a file or pair of files based on SRA identifier

**Comment by andrewmagill** [comment]
Ming completed this a while back.
